# Generated by Django 2.0.5 on 2018-07-03 16:44

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import profile.models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Pelanggan',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('address', models.CharField(default='-', max_length=250)),
                ('phone_number', models.CharField(default='-', max_length=250)),
                ('bio', models.TextField(default='-', max_length=250)),
                ('birth_date', models.DateField(default='-', null=True)),
                ('profile_pic', models.FileField(blank=True, null=True, upload_to=profile.models.Pelanggan.content_file_name)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
