# Generated by Django 2.0.5 on 2018-07-03 17:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('profile', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='pelanggan',
            name='postal_code',
            field=models.CharField(default='-', max_length=10),
        ),
    ]
