# Generated by Django 2.0.5 on 2018-06-17 16:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('profile', '0003_auto_20180612_1436'),
    ]

    operations = [
        migrations.AlterField(
            model_name='customer',
            name='address',
            field=models.CharField(default='-', max_length=250),
        ),
        migrations.AlterField(
            model_name='customer',
            name='bio',
            field=models.TextField(default='-', max_length=250),
        ),
        migrations.AlterField(
            model_name='customer',
            name='birth_date',
            field=models.DateField(default='-', null=True),
        ),
        migrations.AlterField(
            model_name='customer',
            name='phone_number',
            field=models.CharField(default='-', max_length=250),
        ),
    ]
