# Generated by Django 2.0.5 on 2018-06-25 12:26

from django.db import migrations, models
import profile.models


class Migration(migrations.Migration):

    dependencies = [
        ('profile', '0004_auto_20180617_2346'),
    ]

    operations = [
        migrations.AddField(
            model_name='customer',
            name='profile_pic',
            field=models.FileField(blank=True, null=True, upload_to=profile.models.Customer.content_file_name),
        ),
    ]
