# Generated by Django 2.0.5 on 2018-06-23 15:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('order', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='order',
            name='bukti_transfer',
            field=models.ImageField(blank=True, upload_to='transfer/%Y/%m/%d'),
        ),
    ]
