# Generated by Django 2.0.5 on 2018-07-03 16:44

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import produk.models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Kategori',
            fields=[
                ('id_kategori', models.AutoField(primary_key=True, serialize=False)),
                ('nama_kategori', models.CharField(max_length=250)),
            ],
            options={
                'verbose_name': 'category',
                'verbose_name_plural': 'categories',
                'ordering': ('nama_kategori',),
            },
        ),
        migrations.CreateModel(
            name='Produk',
            fields=[
                ('id_produk', models.AutoField(primary_key=True, serialize=False)),
                ('nama_produk', models.CharField(max_length=250)),
                ('stok_produk', models.IntegerField()),
                ('harga_produk', models.IntegerField()),
                ('rating_produk', models.IntegerField(default=0)),
                ('deskripsi', models.TextField(blank=True, max_length=255)),
                ('foto_produk', models.FileField(blank=True, null=True, upload_to=produk.models.Produk.content_file_name)),
                ('kategori_produk', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='kategori', to='produk.Kategori')),
            ],
            options={
                'ordering': ('nama_produk',),
            },
        ),
        migrations.CreateModel(
            name='Rating',
            fields=[
                ('id_rating', models.AutoField(primary_key=True, serialize=False)),
                ('is_rating', models.IntegerField(choices=[(1, '1'), (2, '2'), (3, '3'), (4, '4'), (5, '5')], default=0)),
                ('id_pelanggan', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='rating_pelanggan', to=settings.AUTH_USER_MODEL)),
                ('id_produk', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='rating_id_produk', to='produk.Produk')),
            ],
        ),
        migrations.AlterIndexTogether(
            name='produk',
            index_together={('id_produk', 'kategori_produk')},
        ),
    ]
