# Generated by Django 2.0.4 on 2018-05-04 09:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('produk', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='produk',
            name='deskripsi',
            field=models.TextField(blank=True, max_length=255),
        ),
    ]
