# Generated by Django 2.0.5 on 2018-05-17 05:38

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('produk', '0002_produk_deskripsi'),
    ]

    operations = [
        migrations.CreateModel(
            name='Rating',
            fields=[
                ('id_rating', models.AutoField(primary_key=True, serialize=False)),
                ('is_rating', models.IntegerField(choices=[(1, '1'), (2, '2'), (3, '3'), (4, '4'), (5, '5')], default=0)),
                ('id_pelanggan', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='rating_pelanggan', to=settings.AUTH_USER_MODEL)),
                ('id_produk', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='rating_id_produk', to='produk.Produk')),
            ],
        ),
    ]
