# Generated by Django 2.0.5 on 2018-05-24 07:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('produk', '0003_rating'),
    ]

    operations = [
        migrations.AddField(
            model_name='produk',
            name='synset',
            field=models.CharField(max_length=255, null=True),
        ),
    ]
