# Generated by Django 2.0.5 on 2018-05-24 07:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('produk', '0004_produk_synset'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='produk',
            name='synset',
        ),
        migrations.AddField(
            model_name='kategori',
            name='synset',
            field=models.CharField(max_length=255, null=True),
        ),
    ]
