# Generated by Django 2.0.5 on 2018-06-23 15:36

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('produk', '0005_auto_20180524_1437'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='kategori',
            options={'ordering': ('nama_kategori',), 'verbose_name': 'category', 'verbose_name_plural': 'categories'},
        ),
        migrations.AlterModelOptions(
            name='produk',
            options={'ordering': ('nama_produk',)},
        ),
        migrations.RemoveField(
            model_name='kategori',
            name='synset',
        ),
        migrations.AlterIndexTogether(
            name='produk',
            index_together={('id_produk', 'kategori_produk')},
        ),
    ]
